## Numpy

### Основной класс: np.ndarray

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
%matplotlib notebook

In [2]:
a = np.empty([1, 2, 3])  # empty unintialized array
print(a)

a = np.array([1, 2, 3])  # array from python list/tuple structure
print(a)

[[[2.84178575e-316 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
[1 2 3]


#### Полезные функции для создания np.ndarray

In [3]:
b = np.zeros_like(a)
print(b)

[0 0 0]


In [4]:
b = np.ones_like(a)
print(b)

[1 1 1]


In [5]:
b = np.full(shape=(1, 2), fill_value=3)
print(b)

[[3 3]]


In [6]:
b = np.diag([3, 4, 5])
print(b)

[[3 0 0]
 [0 4 0]
 [0 0 5]]


In [7]:
b = np.linspace(0, 1, 9)
print(b)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


#### Получение информации о массивах

In [8]:
print(type(a), a.size)

<class 'numpy.ndarray'> 3


In [9]:
print(a.dtype, a.itemsize)

int64 8


In [10]:
a = a.astype(np.float64)
print(a)
print(a.dtype, a.itemsize)

[1. 2. 3.]
float64 8


#### Преобразование массивов

In [11]:
# reshape to specific shape
a = np.arange(27).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [12]:
# reshape to (a.size, )
print(a.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [13]:
# to python list
print(a.tolist())

[[[0, 1, 2], [3, 4, 5], [6, 7, 8]], [[9, 10, 11], [12, 13, 14], [15, 16, 17]], [[18, 19, 20], [21, 22, 23], [24, 25, 26]]]


### Операции с массивами

#### Slicing - получение "среза" массива. 

In [14]:
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
# first row
print(a[0, :])

[0 1 2]


In [16]:
# last column
print(a[:, -1])

[2 5 8]


In [17]:
# 'ellipsis' slicing
a = np.arange(27).reshape(3, 3, 3)
print(a)
print(a[0, ...])  # equivalent to a[0, :, :]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Поэлементные операции

In [18]:
# elementwise sin
a = np.arange(9).reshape(3, 3)
print(np.sin(a))

[[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825]]


In [19]:
# python-compatible maths
a = np.arange(9).reshape(3, 3)
print(a**2)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


#### Операции редукции

In [20]:
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
# sum of all elements
print(a.sum())

36


In [22]:
# sum of each row
print(a.sum(axis=1))

[ 3 12 21]


In [23]:
# min over colimns
print(a.min(axis=0))

[0 1 2]


#### Операции, измененяющие размерности массива

In [24]:
a = np.arange(12)
print(a)
a = a.reshape(2, 6)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [25]:
print(a.reshape(3, 2, 2))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [26]:
print(a.swapaxes(0, 1))

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [27]:
a = np.arange(24).reshape(1, 2, 3, 4)
print(a)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]


In [28]:
a = np.arange(24).reshape(1, 2, -1, 4)
print(a)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]


In [29]:
print(a.transpose(0, 1, 3, 2))

[[[[ 0  4  8]
   [ 1  5  9]
   [ 2  6 10]
   [ 3  7 11]]

  [[12 16 20]
   [13 17 21]
   [14 18 22]
   [15 19 23]]]]


In [30]:
print(a.T.shape)  # reverse axis order

(4, 3, 2, 1)


In [31]:
a = np.arange(12).reshape(2, 6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [32]:
print(a[np.newaxis, :, :])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]]


In [33]:
print(a[:, :, np.newaxis])  # add new dimension to the end

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]]


In [34]:
# shorter
print(a[..., None])  # add new dimension to the end

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]]


In [35]:
a = np.arange(12).reshape(2, 6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


__Вопрос:__ Чем отличаются следущие операции? Размерности ведь совпадают...

In [36]:
print(a.reshape(6, 2).shape)
print(a.swapaxes(0, 1).shape)

(6, 2)
(6, 2)


__Ответ:__ операции приводят к разному порядку элементов в массивах.

In [37]:
print(a.reshape(6, 2))
print(a.swapaxes(0, 1))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


#### Fancy Indexing

In [38]:
a = np.arange(12).reshape(2, 6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [39]:
# second and third columns
a[:, [1, 2]]

array([[1, 2],
       [7, 8]])

In [40]:
ix = a > 7
print(ix, ix.dtype)

[[False False False False False False]
 [False False  True  True  True  True]] bool


In [41]:
# boolean indexing
print(a[(a > 7) | (a < 2)])

[ 0  1  8  9 10 11]


#### Broadcasting - если у массива есть размерность с длиной 1, то numpy может автоматически "размножить" данные в ней, сделав длину произвольной. Если даже такой размерности нет, numpy попробует приписать ее в начало.

In [42]:
a = np.arange(6).reshape(2, 3)
b = np.arange(3).reshape(3) + 1
print("A:")
print(a, a.shape)
print("B:")
print(b, b.shape)
print("np.broadcast_to(b, a.shape)")
print(np.broadcast_to(b, a.shape))

A:
[[0 1 2]
 [3 4 5]] (2, 3)
B:
[1 2 3] (3,)
np.broadcast_to(b, a.shape)
[[1 2 3]
 [1 2 3]]


In [43]:
# failed broadcast
a = np.arange(6).reshape(2, 3)
b = np.ones(shape=(2,), dtype=a.dtype)
print("A:")
print(a, a.shape)
print("B:")
print(b, b.shape)
try:
    print("A + B:")
    print(a + b)
except Exception as e:
    print(type(e), e)

A:
[[0 1 2]
 [3 4 5]] (2, 3)
B:
[1 1] (2,)
A + B:
<class 'ValueError'> operands could not be broadcast together with shapes (2,3) (2,) 


In [44]:
# successfull broadcast along last dim
a = np.arange(6).reshape(2, 3)
b = np.ones(shape=(2,), dtype=a.dtype)[:, None]
print("A:")
print(a, a.shape)
print("B:")
print(b, b.shape)
print("A + B:")
print(a + b)

A:
[[0 1 2]
 [3 4 5]] (2, 3)
B:
[[1]
 [1]] (2, 1)
A + B:
[[1 2 3]
 [4 5 6]]


In [45]:
# automatic broadcasting with automatically added first dimention
a = np.arange(6).reshape(2, 3)
b = np.ones(shape=(3,), dtype=a.dtype)
print("A:")
print(a, a.shape)
print("B:")
print(b, b.shape)
print("A + B:")
print(a + b)

A:
[[0 1 2]
 [3 4 5]] (2, 3)
B:
[1 1 1] (3,)
A + B:
[[1 2 3]
 [4 5 6]]


In [46]:
# bcast over two or more axes:
a = np.arange(6).reshape(2, 3)
b = np.ones(shape=(6,), dtype=a.dtype).reshape(2, 3)
print("A:")
print(a)
print("B:")
print(b)
print("A + B:")
print(a[None, :, :] + b[:, None, :])

A:
[[0 1 2]
 [3 4 5]]
B:
[[1 1 1]
 [1 1 1]]
A + B:
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### Операция .dot — обобщённое матричное умножение

In [47]:
a = np.arange(6)
b = np.arange(6)
print(a)
print(b)

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [48]:
# two vector dot product
print(a.dot(b))
print(np.dot(a, b))

55
55


In [49]:
# matrix-vector product
a = np.arange(6).reshape(3, 2)
b = np.arange(2) + 1
print(a)
print(b)
print(a.dot(b))

[[0 1]
 [2 3]
 [4 5]]
[1 2]
[ 2  8 14]


In [50]:
# wrong alignment!
try:
    print(a.dot(b.reshape(1, 2)))
except Exception as e:
    print(type(e), e)

<class 'ValueError'> shapes (3,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)


In [51]:
# matrix-matrix product
a = np.arange(6).reshape(3, 2)
b = np.arange(8).reshape(2, 4)
print(a.shape)
print(b.shape)
print(a.dot(b).shape)

(3, 2)
(2, 4)
(3, 4)


## Example: Linear system solution
Let's say we want to solve $Ax = b$.  
  
Solution may not exist, so let's solve $x = argmin\space||Ax - b||_2^2$ with respect to $x$.  
  
Optimal solution: $x = (A^T A)^{-1}A^Tb$.  
  
$(A^T A)^{-1}$ is guaranteed to exist.

In [52]:
A = np.random.uniform(-1, 1, size=(3, 3))
b = np.random.uniform(-1, 1, size=(3,))

In [53]:
x = np.linalg.inv(A.T.dot(A)).dot(A.T).dot(b)

In [54]:
assert np.linalg.norm(A.dot(x) - b) < 1e-6